version: "3.9"
   
services:
  server:
    image: malpel/tt-rest:latest
    ports: 
      - "3001:3001"
    environment:
      - PORT=3001
  client:
    image: malpel/tt-client:latest
    ports:
      - "3000:80"