name: E2E

on:
  push:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Compose
        run: docker-compose up -d

    container: cypress/included:4.11.0
    steps:
      - uses: actions/checkout@v1
      - run: cypress run

      
