name: E2E

on:
  push:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Compose
        run: docker-compose up -d

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: my-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - run: npm i cypress
      - uses: cypress-io/github-action@v2
        with:
          install: false 

      
