name: E2E

on:
  push:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Compose
        run: docker-compose up -d
      - name: Switch directory
        run: cd client

      - name: Cypress run
        uses: cypress-io/github-action@v2
    

      
