name: Testing

on:
  push:
    branches:
      - main

jobs:
  testing_pipeline:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: server
    #services:
      # Label used to access the service container
      
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1        
      with:
        node-version: '16.8.0'
    - name: npm install 
      run: npm install
    - name: run lint
      run: npm run lint
    - name: run jest tests
      env:
        PORT: ${{ secrets.PORT }}
      run: npm test

  Push_to_Docker:
    name: Push image to DockerHub
    runs-on: ubuntu-latest
    needs: testing_pipeline
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          context: server
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: malpel/tt-rest:latest
