name: Testing

on:
  push:
    branches:
      - main

jobs:
  testing_pipeline:
    runs-on: ubuntu-20.04
    #services:
      # Label used to access the service container
      
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1        
    - name: npm install, lint, and test
      working-directory: server
      run: |
          npm install
          npm test
          npm run start:test
      env:
        PORT: ${{ secrets.PORT }}

  Push_server_to_Docker:
    name: Push server image to Docker Hub
    runs-on: ubuntu-latest
    needs: testing_pipeline
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: malpel/tt-rest:latest
          context: .
          file: ./server/Dockerfile

  Push_client_to_Docker:
    name: Push client image to Docker Hub
    needs: testing_pipeline
    runs-on: ubuntu-latest
    #needs: testing_pipeline
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: malpel/tt-client:latest
          context: .
          file: ./client/Dockerfile

      
